- name: Module and network config
  shell: |
    cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
    overlay
    br_netfilter
    EOF

    modprobe overlay
    modprobe br_netfilter

    cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.ipv4.ip_forward                 = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    EOF

    sysctl --system

- name: Update repos
  shell: |
    apt update

- name: Install dependencies
  ansible.builtin.package:
    name: 
      - sshpass
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: latest

- name: Install kubernetes libraries
  shell: python3 -m pip install kubernetes

- name: Add containerd gpg key and repo
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update repos
  shell: |
    apt update

- name: Install containerd
  ansible.builtin.package:
    name: containerd.io
    state: latest

- name: Configure containerd
  shell: |
    mkdir -p /etc/containerd
    containerd config default | sudo tee /etc/containerd/config.toml
    systemctl restart containerd
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Add k8s gpg key and repo
  shell: |
    sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Update repos
  shell: |
    apt update

- name: Install k8s
  ansible.builtin.package:
    name: 
      - 'kubelet={{ KUBERNETES_VERSION }}-00'
      - 'kubeadm={{ KUBERNETES_VERSION }}-00'
      - 'kubectl={{ KUBERNETES_VERSION }}-00'
    state: present

- name: Hold k8s packages
  shell: |
    apt-mark hold kubelet kubeadm kubectl

- name: Create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: '0755'
